### ISSUE TITLE
[server]/api/v1/report/webscript 404 (Not Found)

### ISSUE THREAD

**Issue by Lanseria** [wangweianger/web-report-sdk#1]
是什么原因造成跨域请求这个地址404?

`option` 204接下来就没有请求了

**Comment by wangweianger** [comment]
@Lanseria 你好这是跨域导致的结果 你需要配置域名白名单 domainWhiteList

**Comment by wangweianger** [comment]
你好这是跨域导致的结果 你需要配置域名白名单 domainWhiteList 
同时不建议你使用script脚本，建议你使用 web-report-sdk 进行上报
![image](https://user-images.githubusercontent.com/16434497/48246047-c8978c80-e428-11e8-8814-f7d5dce82e07.png)

**Comment by qmxcompanyweb** [comment]
如果你是线上访问本地服务是访问不通的发自我的iPhone------------------ Original ------------------From: vhikZhangchao  <notifications@github.com>Date: Fri,Nov 9,2018 2:28 PMTo: wangweianger/web-report-sdk <web-report-sdk@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: Re: [wangweianger/web-report-sdk] [server]/api/v1/report/webscript404 (Not Found) (#1)
设置过了还是不行

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/wangweianger/web-report-sdk","title":"wangweianger/web-report-sdk","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/wangweianger/web-report-sdk"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Lanseria in #1: ![image](https://user-images.githubusercontent.com/14802764/48246764-a5baa780-e42b-11e8-82a4-f686536fed54.png)\r\n设置过了还是不行"}],"action":{"name":"View Issue","url":"https://github.com/wangweianger/web-report-sdk/issues/1#issuecomment-437263631"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/wangweianger/web-report-sdk/issues/1#issuecomment-437263631",
"url": "https://github.com/wangweianger/web-report-sdk/issues/1#issuecomment-437263631",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [wangweianger/web-report-sdk] [server]/api/v1/report/webscript 404 (Not Found) (#1)",
"sections": [
{
"text": "",
"activityTitle": "**vhikZhangchao**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Lanseria",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"wangweianger/web-report-sdk\",\n\"issueId\": 1,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"wangweianger/web-report-sdk\",\n\"issueId\": 1\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/wangweianger/web-report-sdk/issues/1#issuecomment-437263631"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 408422757\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by Lanseria** [comment]
@qmxcompanyweb 是路径错了
